from typing import Any

from .. import _misc


class FieldWrapper(metaclass=_misc.SimpleMeta):
    __abstract__: bool = ...
    __static__: bool | None = ...

    is_function: bool = ...

    def __init__(self, value: Any) -> None: ...

    value: Any = ...

