from .._meta import *
from typing import overload, Any
from types import FunctionType, CodeType


class SimpleFunction(metaclass=MultiMeta):
    @overload
    def __init__(self, function: FunctionType) -> None: ...
    @overload
    def __init__(self, code: CodeType, globals: dict[str, Any],
                 name: str = ..., argdefs: tuple = ..., closure: tuple = ...) -> None: ...
    __closure__: tuple = ...
    __code__: CodeType = ...
    __defaults__: tuple = ...
    __globals__: dict[str, Any] = ...
    __kwdefaults__: dict = ...

