from .._meta import *
from _ctypes import CFuncPtr
from typing import overload

class Library(metaclass=MultiMeta):
    def __init__(self, handle: int) -> None: ...
    def __getattr__(self, item: str) -> CFuncPtr: ...
    @overload
    def find_reference(self, name: str, flags: int = ...) -> CFuncPtr: ...
    @overload
    def find_reference(self, ordinal: int, flags: int = ...) -> CFuncPtr: ...
    @staticmethod
    def Load(name: str, flags: int = ...) -> Library: ...

